version: '3'
services:
  s3:
    image: minio/minio
    ports:
      - "9020:9000"
    volumes:
      - "./tmp:/home"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMIK7MDENGWbPxRfiCYEXAMPLEKEY"
    command: server /home
